@startuml Library
!theme vibrant
skinparam linetype ortho


class Library {
    -name: String
}

abstract class Book {
    -title: String
    -author: String
    -ISBN: String
    -genre: Genre
    -isAvailable: boolean
}

enum Genre {
    Fiction
    Drama
    Fantasy
    Mystery
}

class Ebook {
    -fileFormat: String
    -fileSize: double
}

class PrintedBook {
    -pagesCount: int
    -physicalCondition: PhysicalCondition
}

enum PhysicalCondition {
    New
    Good
    Worn   
}

abstract class Person {
    -name: String
    -contactInfo: String
}

class Librarian {
    -staffID: String
    +addBook(String)
    +removeBook(String)
    +updateBookInfo(String)
}

class Member {
    -memberID: String
    -currentBorrowedBooks: Integer
    +borrowBook(book: Book, borrowDate: Date,\n dueDate: Date)
}

class BorrowedHistory {
    -book: Book
    -borrowDate: Date
    -returnDate: Date 
}

class BorrowingSystem {
    -member: Member
    -book: Book
    -borrowDate: Date
    -dueDate: Date
    +listBorrowedByMember(member: Member)
    +listBorrowedByBook(book: Book)
    +returnBook(book: Book)
}

Book <|-- Ebook
Book <|-- PrintedBook


Person <|-- Librarian
Person <|-- Member 

Member *-[norank]- BorrowedHistory

BorrowingSystem --> Member : tracks
BorrowingSystem --> Book : tracks
BorrowingSystem --> BorrowedHistory : creates

Library *-- Librarian : employs
Library o-- Book : has
Library *-[norank]- Member : owns
Library --> BorrowingSystem : manages

@enduml
