@startuml Library
!theme vibrant
skinparam linetype ortho


class Library{
-branchName: String
}

abstract class Book {
-title: String
-author: String
-ISBN: String
-genre: Genre
-isAvailable: boolean
}

enum Genre {
    Fiction
    Drama
    Fantasy
    Mystery
}

class Ebook{
-fileFormat: String
-fileSize: double
}

class PrintedBook{
-pagesCount:int
-physicalCondition: PhysicalCondition

}

enum PhysicalCondition {
New
Good
Worn   
}

class Member{
-name: String
-memberID: String
-contactInfo: String
-currentBorrowedBooks: Integer
+borrowBook(book:Book,borrowDate:Date,dueDate:Date)

}

class BorrowedBookHistory {
-book: Book
-borrowDate: Date
-returnDate: Date 
}

class Librarian{
-staffID: String
-name: String
-contact: String
+addBook(String)
+removeBook(String)
+updateBookInfo(String)
}

class BorrowingSystem{
-member: Member
-book: Book
-borrowDate:Date
-dueDate:Date
+trackBorrowByMember(member: Member)
+trackBorrowByBook(book: Book)
+returnBook(book: Book)

}

Book <|-- Ebook
Book <|-- PrintedBook

Member*--BorrowedBookHistory

BorrowingSystem --> Member : tracks
BorrowingSystem --> Book : tracks
BorrowingSystem -->BorrowedBookHistory: creates

Library o-- Book : has
Library o-- Member : has
Library o-- Librarian : has
Library --> BorrowingSystem : manages
@enduml